In [1]:
import pandas as pd
import math
df=pd.read_csv("survey_results_public.csv")
df_schema=pd.read_csv("survey_results_schema.csv")
people={"first":["Rajat","Corey","John"],
        "last":["Gupta","Sch","Doe"],
        "email":["RajatGupta@email.com","corey@email.com","john@email.com"]}
df2=pd.DataFrame(people)

In [2]:
df["ConvertedComp"].mean()

103756.05014961446

In [3]:
df["ConvertedComp"].median()

54049.0

In [4]:
df.median()

Respondent       32231.0
Age                 29.0
CompTotal        63000.0
ConvertedComp    54049.0
WorkWeekHrs         40.0
dtype: float64

In [5]:
df.max()

Respondent        6.563900e+04
Age               2.790000e+02
CompTotal        1.111111e+247
ConvertedComp     2.000000e+06
WorkWeekHrs       4.750000e+02
dtype: float64

In [6]:
df["Age"].max()

279.0

In [7]:
f=df["Age"]==279

In [8]:
df[f]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
14375,14419,I am a developer by profession,Yes,279.0,16,Yearly,49000.0,52968.0,Netherlands,European Euro,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",NaN,React.js,Just as welcome now as I felt last year,40.0,7,3

In [9]:
df.describe()

         Respondent           Age      CompTotal  ConvertedComp   WorkWeekHrs
count  64461.000000  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean   32554.079738     30.834111  3.190464e+242   1.037561e+05     40.782174
std    18967.442360      9.585392            inf   2.268853e+05     17.816383
min        1.000000      1.000000   0.000000e+00   0.000000e+00      1.000000
25%    16116.000000     24.000000   2.000000e+04   2.464800e+04     40.000000
50%    32231.000000     29.000000   6.300000e+04   5.404900e+04     40.000000
75%    49142.000000     35.000000   1.250000e+05   9.500000e+04     44.000000
max    65639.000000    279.000000  1.111111e+247   2.000000e+06    475.000000

In [10]:
df["ConvertedComp"].describe()

count    3.475600e+04
mean     1.037561e+05
std      2.268853e+05
min      0.000000e+00
25%      2.464800e+04
50%      5.404900e+04
75%      9.500000e+04
max      2.000000e+06
Name: ConvertedComp, dtype: float64

In [11]:
df.count()

Respondent            64461
MainBranch            64162
Hobbyist              64416
Age                   45446
Age1stCode            57900
                      ...
WebframeWorkedWith    42279
WelcomeChange         52683
WorkWeekHrs           41151
YearsCode             57684
YearsCodePro          46349
Length: 61, dtype: int64

In [12]:
df["ConvertedComp"].count()

34756

In [13]:
df["ConvertedComp"].value_counts()

120000.0     341
100000.0     306
150000.0     277
2000000.0    258
1000000.0    258
            ...
102700.0       1
68721.0        1
96250.0        1
38456.0        1
21487.0        1
Name: ConvertedComp, Length: 6958, dtype: int64

In [14]:
df["Hobbyist"].value_counts()

Yes    50388
No     14028
Name: Hobbyist, dtype: int64

In [15]:
pd.set_option("display.max_columns",61)

In [16]:
df

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"Iâ€™m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64456,64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64457,64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64458,64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64459,64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
64460,65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [17]:
df_schema

                Column                                       QuestionText
0           Respondent  Randomized respondent ID number (not in order ...
1           MainBranch  Which of the following options best describes ...
2             Hobbyist                            Do you code as a hobby?
3                  Age  What is your age (in years)? If you prefer not...
4           Age1stCode  At what age did you write your first line of c...
..                 ...                                                ...
56  WebframeWorkedWith  Which web frameworks have you done extensive d...
57       WelcomeChange  Compared to last year, how welcome do you feel...
58         WorkWeekHrs  On average, how many hours per week do you wor...
59           YearsCode  Including any education, how many years have y...
60        YearsCodePro  NOT including education, how many years have y...

[61 rows x 2 columns]

In [18]:
df_schema.set_index("Column",inplace=True)

In [19]:
pd.set_option("display.max_row",61)

In [20]:
df_schema

                                                                   QuestionText
Column
Respondent                    Randomized respondent ID number (not in order ...
MainBranch                    Which of the following options best describes ...
Hobbyist                                                Do you code as a hobby?
Age                           What is your age (in years)? If you prefer not...
Age1stCode                    At what age did you write your first line of c...
CompFreq                       Is that compensation weekly, monthly, or yearly?
CompTotal                     What is your current total compensation (salar...
ConvertedComp                 Salary converted to annual USD salaries using ...
Country                                                      Where do you live?
CurrencyDesc                  Which currency do you use day-to-day? If your ...
CurrencySymbol                Which currency do you use day-to-day? If your ...
DatabaseDesireNextYear        Which database environments have you done exte...
DatabaseWorkedWith            Which database environments have you done exte...
DevType                       Which of the following describe you? Please se...
EdLevel                       Which of the following best describes the high...
Employment                    Which of the following best describes your cur...
Ethnicity                     Which of the following describe you, if any? P...
Gender                        Which of the following describe you, if any? P...
JobFactors                    Imagine that you are deciding between two job ...
JobSat                        How satisfied are you with your current job? (...
JobSeek                       Which of the following best describes your cur...
LanguageDesireNextYear        Which programming, scripting, and markup langu...
LanguageWorkedWith            Which programming, scripting, and markup langu...
MiscTechDesireNextYear        Which other frameworks, libraries, and tools h...
MiscTechWorkedWith            Which other frameworks, libraries, and tools h...
NEWCollabToolsDesireNextYear  Which collaboration tools have you done extens...
NEWCollabToolsWorkedWith      Which collaboration tools have you done extens...
NEWDevOps                     Does your company have a dedicated DevOps person?
NEWDevOpsImpt                 How important is the practice of DevOps to sca...
NEWEdImpt                     How important is a formal education, such as a...
NEWJobHunt                    In general, what drives you to look for a new ...
NEWJobHuntResearch            When job searching, how do you learn more abou...
NEWLearn                      How frequently do you learn a new language or ...
NEWOffTopic                   Do you think Stack Overflow should relax restr...
NEWOnboardGood                Do you think your company has a good onboardin...
NEWOtherComms                 Are you a member of any other online developer...
NEWOvertime                   How often do you work overtime or beyond the f...
NEWPurchaseResearch           When buying a new tool or software, how do you...
NEWPurpleLink                 You search for a coding solution online and th...
NEWSOSites                    Which of the following Stack Overflow sites ha...
NEWStuck                      What do you do when you get stuck on a problem...
OpSys                         What is the primary operating system in which ...
OrgSize                       Approximately how many people are employed by ...
PlatformDesireNextYear        Which platforms have you done extensive develo...
PlatformWorkedWith            Which platforms have you done extensive develo...
PurchaseWhat                  What level of influence do you, personally, ha...
Sexuality                     Which of the following describe you, if any? P...
SOAccount                                 Do you have a Stack Overflow account?
SOComm                        Do you consider yourself a member of the Stack...
SOPartFreq                    How frequently would you say you participate i...
SOVisitFreq                   How frequently would you say you visit Stack O...
SurveyEase                    How easy or difficult was this survey to compl...
SurveyLength                  How do you feel about the length of the survey...
Trans                                                      Are you transgender?
UndergradMajor                            What was your primary field of study?
WebframeDesireNextYear        Which web frameworks have you done extensive d...
WebframeWorkedWith            Which web frameworks have you done extensive d...
WelcomeChange                 Compared to last year, how welcome do you feel...
WorkWeekHrs                   On average, how many hours per week do you wor...
YearsCode                     Including any education, how many years have y...
YearsCodePro                  NOT including education, how many years have y...

In [21]:
df_schema["QuestionText"]["SOPartFreq"]

'How frequently would you say you participate in Q&A on Stack Overflow? By participate we mean ask, answer, vote for, or comment on questions.'

In [22]:
df["SOPartFreq"].value_counts()

Less than once per month or monthly                   20432
I have never participated in Q&A on Stack Overflow    10427
A few times per month or weekly                        8317
A few times per week                                   4193
Daily or almost daily                                  2198
Multiple times per day                                 1225
Name: SOPartFreq, dtype: int64

In [23]:
df["SOPartFreq"].value_counts(normalize=True)

Less than once per month or monthly                   0.436656
I have never participated in Q&A on Stack Overflow    0.222837
A few times per month or weekly                       0.177744
A few times per week                                  0.089609
Daily or almost daily                                 0.046974
Multiple times per day                                0.026180
Name: SOPartFreq, dtype: float64

In [24]:
df["Country"].value_counts()

United States     12469
India              8403
United Kingdom     3896
Germany            3890
Canada             2191
                  ...
Lesotho               1
Kiribati              1
Nauru                 1
Grenada               1
Saint Lucia           1
Name: Country, Length: 183, dtype: int64

In [25]:
df.groupby(["Country"])

In [26]:
country_grp=df.groupby(["Country"])

In [27]:
country_grp.get_group("India")

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, front-end;Devel...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;HTML/CSS;PHP,C#;HTML/CSS;PHP,NaN,NaN,NaN,NaN,Yes,Extremely important,Very important,Better compensation;Growth or leadership oppor...,"Read company media, such as employee blogs or ...",Every few months,Yes,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Windows,20 to 99 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,NaN,NaN,"Developer, full-stack;Engineer, data","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,Slightly dissatisfied,I am actively looking for a job,Java;JavaScript;Python,Java;Python,NaN,NaN,NaN,NaN,Not sure,NaN,Very important,Better compensation;Better work/life balance;W...,Company reviews from third party sites (e.g. G...,Every few months,No,Yes,No,Often: 1-2 days per week or more,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Windows,500 to 999 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
57,58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,INR,Microsoft SQL Server,Microsoft SQL Server,"Developer, back-end",NaN,"Independent contractor, freelancer, or self-em...",South Asian,NaN,Family friendliness,Very satisfied,I am not interested in new job opportunities,C#;JavaScript;SQL;TypeScript,C#;JavaScript;SQL;TypeScript,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Stack Overflow for Teams,Stack Overflow for Teams,Yes,Extremely important,Very important,NaN,NaN,Once every few years,NaN,Yes,No,Often: 1-2 days per week or more,Ask developers I know/work with,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",NaN,Multiple times per day,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
62,63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,NaN,DynamoDB,Firebase;MongoDB;MySQL,"Designer;Developer, back-end;Developer, front-...","Secondary school (e.g. American high school, G...","Not employed, but looking for work",South Asian,Man,Flex time or a flexible schedule;How widely us...,NaN,I am actively looking for a job,Go;Kotlin;TypeScript,C;C++;HTML/CSS;Java;JavaScript;Python,Flutter;Node.js;React Native;TensorFlow,NaN,Confluence;Stack Overflow for Teams,Github;Facebook Workplace;Slack;Microsoft Team...,NaN,NaN,NaN,NaN,NaN,Once a year,Yes,NaN,No,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,NaN,AWS;Docker;Heroku;iOS,Android;Arduino;Google Cloud Platform;Raspberr...,NaN,Straight / Heterosexual,Yes,Neutral,A few times per week,Daily or almost daily,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
147,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,INR,Cassandra;MySQL;PostgreSQL,MySQL;PostgreSQL,"Developer, back-end;Developer, QA or test;DevO...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,East Asian,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;C;C++;Java;Perl;Scala,Bash/Shell/PowerShell;C++;Perl,Apache Spark,NaN,Confluence;Jira;Github;Gitlab;Google Suite (Do...,"Confluence;Jira;Github;Google Suite (Docs, Mee...",Not sure,Neutral,Critically important,Just because;Curious about other opportunities...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,Indifferent,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Linux-based,500 to 999 employees,Google Cloud Platform;Linux,Linux,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64391,54757,NaN,Yes,NaN,18,NaN,NaN,NaN,India,NaN,NaN,MongoDB;MySQL,MySQL,"Developer, full-stack;Developer, QA or test","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL,C;HTML/CSS;Java;JavaScript;PHP;Python;SQL,NaN,NaN,Jira;Github;Gitlab;Slack,Jira;Github;Gitlab;Slack,NaN,NaN,NaN,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Linux-based,NaN,Linux;Windows,Linux;Windows,NaN,Straight / Heterosexual,Not sure/can't remember,Neutral,NaN,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,A lot less welcome now than last year,NaN,5,Less than 1 year
64398,55407,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Associate degree (A.A., A.S., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64439,62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
64442,62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64452,64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df[df["Country"]=="India"]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, front-end;Devel...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;HTML/CSS;PHP,C#;HTML/CSS;PHP,NaN,NaN,NaN,NaN,Yes,Extremely important,Very important,Better compensation;Growth or leadership oppor...,"Read company media, such as employee blogs or ...",Every few months,Yes,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Windows,20 to 99 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,NaN,NaN,"Developer, full-stack;Engineer, data","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,Slightly dissatisfied,I am actively looking for a job,Java;JavaScript;Python,Java;Python,NaN,NaN,NaN,NaN,Not sure,NaN,Very important,Better compensation;Better work/life balance;W...,Company reviews from third party sites (e.g. G...,Every few months,No,Yes,No,Often: 1-2 days per week or more,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Windows,500 to 999 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
57,58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,INR,Microsoft SQL Server,Microsoft SQL Server,"Developer, back-end",NaN,"Independent contractor, freelancer, or self-em...",South Asian,NaN,Family friendliness,Very satisfied,I am not interested in new job opportunities,C#;JavaScript;SQL;TypeScript,C#;JavaScript;SQL;TypeScript,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Stack Overflow for Teams,Stack Overflow for Teams,Yes,Extremely important,Very important,NaN,NaN,Once every few years,NaN,Yes,No,Often: 1-2 days per week or more,Ask developers I know/work with,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",NaN,Multiple times per day,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
62,63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,NaN,DynamoDB,Firebase;MongoDB;MySQL,"Designer;Developer, back-end;Developer, front-...","Secondary school (e.g. American high school, G...","Not employed, but looking for work",South Asian,Man,Flex time or a flexible schedule;How widely us...,NaN,I am actively looking for a job,Go;Kotlin;TypeScript,C;C++;HTML/CSS;Java;JavaScript;Python,Flutter;Node.js;React Native;TensorFlow,NaN,Confluence;Stack Overflow for Teams,Github;Facebook Workplace;Slack;Microsoft Team...,NaN,NaN,NaN,NaN,NaN,Once a year,Yes,NaN,No,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,NaN,AWS;Docker;Heroku;iOS,Android;Arduino;Google Cloud Platform;Raspberr...,NaN,Straight / Heterosexual,Yes,Neutral,A few times per week,Daily or almost daily,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
147,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,INR,Cassandra;MySQL;PostgreSQL,MySQL;PostgreSQL,"Developer, back-end;Developer, QA or test;DevO...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,East Asian,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;C;C++;Java;Perl;Scala,Bash/Shell/PowerShell;C++;Perl,Apache Spark,NaN,Confluence;Jira;Github;Gitlab;Google Suite (Do...,"Confluence;Jira;Github;Google Suite (Docs, Mee...",Not sure,Neutral,Critically important,Just because;Curious about other opportunities...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,Indifferent,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Linux-based,500 to 999 employees,Google Cloud Platform;Linux,Linux,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64391,54757,NaN,Yes,NaN,18,NaN,NaN,NaN,India,NaN,NaN,MongoDB;MySQL,MySQL,"Developer, full-stack;Developer, QA or test","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL,C;HTML/CSS;Java;JavaScript;PHP;Python;SQL,NaN,NaN,Jira;Github;Gitlab;Slack,Jira;Github;Gitlab;Slack,NaN,NaN,NaN,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Linux-based,NaN,Linux;Windows,Linux;Windows,NaN,Straight / Heterosexual,Not sure/can't remember,Neutral,NaN,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,A lot less welcome now than last year,NaN,5,Less than 1 year
64398,55407,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Associate degree (A.A., A.S., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64439,62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
64442,62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64452,64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
filt=df["Country"]=="India"

In [30]:
df[filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, front-end;Devel...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;HTML/CSS;PHP,C#;HTML/CSS;PHP,NaN,NaN,NaN,NaN,Yes,Extremely important,Very important,Better compensation;Growth or leadership oppor...,"Read company media, such as employee blogs or ...",Every few months,Yes,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Windows,20 to 99 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,NaN,NaN,"Developer, full-stack;Engineer, data","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,Slightly dissatisfied,I am actively looking for a job,Java;JavaScript;Python,Java;Python,NaN,NaN,NaN,NaN,Not sure,NaN,Very important,Better compensation;Better work/life balance;W...,Company reviews from third party sites (e.g. G...,Every few months,No,Yes,No,Often: 1-2 days per week or more,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Windows,500 to 999 employees,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
57,58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,INR,Microsoft SQL Server,Microsoft SQL Server,"Developer, back-end",NaN,"Independent contractor, freelancer, or self-em...",South Asian,NaN,Family friendliness,Very satisfied,I am not interested in new job opportunities,C#;JavaScript;SQL;TypeScript,C#;JavaScript;SQL;TypeScript,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Stack Overflow for Teams,Stack Overflow for Teams,Yes,Extremely important,Very important,NaN,NaN,Once every few years,NaN,Yes,No,Often: 1-2 days per week or more,Ask developers I know/work with,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, definitely",NaN,Multiple times per day,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
62,63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,NaN,DynamoDB,Firebase;MongoDB;MySQL,"Designer;Developer, back-end;Developer, front-...","Secondary school (e.g. American high school, G...","Not employed, but looking for work",South Asian,Man,Flex time or a flexible schedule;How widely us...,NaN,I am actively looking for a job,Go;Kotlin;TypeScript,C;C++;HTML/CSS;Java;JavaScript;Python,Flutter;Node.js;React Native;TensorFlow,NaN,Confluence;Stack Overflow for Teams,Github;Facebook Workplace;Slack;Microsoft Team...,NaN,NaN,NaN,NaN,NaN,Once a year,Yes,NaN,No,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,NaN,AWS;Docker;Heroku;iOS,Android;Arduino;Google Cloud Platform;Raspberr...,NaN,Straight / Heterosexual,Yes,Neutral,A few times per week,Daily or almost daily,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
147,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,INR,Cassandra;MySQL;PostgreSQL,MySQL;PostgreSQL,"Developer, back-end;Developer, QA or test;DevO...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,East Asian,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;C;C++;Java;Perl;Scala,Bash/Shell/PowerShell;C++;Perl,Apache Spark,NaN,Confluence;Jira;Github;Gitlab;Google Suite (Do...,"Confluence;Jira;Github;Google Suite (Docs, Mee...",Not sure,Neutral,Critically important,Just because;Curious about other opportunities...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,Indifferent,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Linux-based,500 to 999 employees,Google Cloud Platform;Linux,Linux,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64391,54757,NaN,Yes,NaN,18,NaN,NaN,NaN,India,NaN,NaN,MongoDB;MySQL,MySQL,"Developer, full-stack;Developer, QA or test","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL,C;HTML/CSS;Java;JavaScript;PHP;Python;SQL,NaN,NaN,Jira;Github;Gitlab;Slack,Jira;Github;Gitlab;Slack,NaN,NaN,NaN,NaN,NaN,Once a year,No,NaN,NaN,NaN,Ask developers I know/work with,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Linux-based,NaN,Linux;Windows,Linux;Windows,NaN,Straight / Heterosexual,Not sure/can't remember,Neutral,NaN,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,A lot less welcome now than last year,NaN,5,Less than 1 year
64398,55407,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Associate degree (A.A., A.S., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64439,62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
64442,62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64452,64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df.loc[filt,"SOVisitFreq"].value_counts()

Multiple times per day                                2649
Daily or almost daily                                 2202
A few times per week                                  1112
A few times per month or weekly                        625
Less than once per month or monthly                    173
I have never visited Stack Overflow (before today)      38
Name: SOVisitFreq, dtype: int64

In [32]:
df.loc[filt]["SOVisitFreq"].value_counts()

Multiple times per day                                2649
Daily or almost daily                                 2202
A few times per week                                  1112
A few times per month or weekly                        625
Less than once per month or monthly                    173
I have never visited Stack Overflow (before today)      38
Name: SOVisitFreq, dtype: int64

In [33]:
df[filt]["SOVisitFreq"].value_counts()

Multiple times per day                                2649
Daily or almost daily                                 2202
A few times per week                                  1112
A few times per month or weekly                        625
Less than once per month or monthly                    173
I have never visited Stack Overflow (before today)      38
Name: SOVisitFreq, dtype: int64

In [34]:
country_grp["SOVisitFreq"].value_counts()

Country      SOVisitFreq
Afghanistan  Daily or almost daily                                 12
             Multiple times per day                                12
             A few times per week                                  10
             A few times per month or weekly                        6
             I have never visited Stack Overflow (before today)     4
                                                                   ..
Zimbabwe     A few times per month or weekly                        8
             Daily or almost daily                                  8
             Multiple times per day                                 7
             A few times per week                                   3
             Less than once per month or monthly                    2
Name: SOVisitFreq, Length: 761, dtype: int64

In [35]:
country_grp["SOVisitFreq"].value_counts().loc["India"]

SOVisitFreq
Multiple times per day                                2649
Daily or almost daily                                 2202
A few times per week                                  1112
A few times per month or weekly                        625
Less than once per month or monthly                    173
I have never visited Stack Overflow (before today)      38
Name: SOVisitFreq, dtype: int64

In [68]:
country_grp["SOVisitFreq"].value_counts(normalize=True).loc["India"]

SOVisitFreq
Multiple times per day                                0.389616
Daily or almost daily                                 0.323871
A few times per week                                  0.163553
A few times per month or weekly                       0.091925
Less than once per month or monthly                   0.025445
I have never visited Stack Overflow (before today)    0.005589
Name: SOVisitFreq, dtype: float64

In [37]:
country_grp["ConvertedComp"].median()

Country
Afghanistan                             15163.5
Albania                                 15900.0
Algeria                                  9432.0
Andorra                                 88640.0
Angola                                   5292.0
                                         ...
Venezuela, Bolivarian Republic of...     3600.0
Viet Nam                                10344.0
Yemen                                   36000.0
Zambia                                   5452.0
Zimbabwe                                 7200.0
Name: ConvertedComp, Length: 183, dtype: float64

In [38]:
country_grp["ConvertedComp"].median().loc["Germany"]

62697.0

In [39]:
country_grp["ConvertedComp"].agg(["median","mean"])

                                       median           mean
Country
Afghanistan                           15163.5  148290.125000
Albania                               15900.0   25611.000000
Algeria                                9432.0   10362.812500
Andorra                               88640.0   88640.000000
Angola                                 5292.0    5292.000000
...                                       ...            ...
Venezuela, Bolivarian Republic of...   3600.0    6280.611111
Viet Nam                              10344.0   28342.605769
Yemen                                 36000.0   36000.000000
Zambia                                 5452.0   17506.400000
Zimbabwe                               7200.0   26338.181818

[183 rows x 2 columns]

In [40]:
country_grp["ConvertedComp"].agg(["mean","median"]).loc["India"]

mean      28751.271364
median    10056.000000
Name: India, dtype: float64

In [41]:
filt=df["Country"]=="India"

In [42]:
df.loc[filt,"LanguageWorkedWith"]

6                                  C#;HTML/CSS;PHP
21                                     Java;Python
57                    C#;JavaScript;SQL;TypeScript
62           C;C++;HTML/CSS;Java;JavaScript;Python
147                 Bash/Shell/PowerShell;C++;Perl
                           ...
64391    C;HTML/CSS;Java;JavaScript;PHP;Python;SQL
64398                                          NaN
64439                                          NaN
64442                                          SQL
64452                                          NaN
Name: LanguageWorkedWith, Length: 8403, dtype: object

In [43]:
df.loc[filt,"LanguageWorkedWith"].str.contains("Python")

6        False
21        True
57       False
62        True
147      False
         ...
64391     True
64398      NaN
64439      NaN
64442    False
64452      NaN
Name: LanguageWorkedWith, Length: 8403, dtype: object

In [44]:
df.loc[filt,"LanguageWorkedWith"].str.contains("Python").sum()

2670

In [45]:
country_grp["LanguageWorkedWith"].str.contains("Python").sum().loc["India"]

AttributeError: Cannot access attribute 'str' of 'SeriesGroupBy' objects, try using the 'apply' method

In [46]:
country_grp["LanguageWorkedWith"].apply(lambda x:x)

0                                   C#;HTML/CSS;JavaScript
1                                         JavaScript;Swift
2                                 Objective-C;Python;Swift
3                                                      NaN
4                                        HTML/CSS;Ruby;SQL
                               ...
64456                                                  NaN
64457    Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
64458                                                  NaN
64459                                             HTML/CSS
64460                      C#;HTML/CSS;Java;JavaScript;SQL
Name: LanguageWorkedWith, Length: 64461, dtype: object

In [47]:
country_grp["LanguageWorkedWith"].apply(lambda x:x.str.contains("Python"))

0        False
1        False
2         True
3          NaN
4        False
         ...
64456      NaN
64457     True
64458      NaN
64459    False
64460    False
Name: LanguageWorkedWith, Length: 64461, dtype: object

In [70]:
country_grp["LanguageWorkedWith"].apply(lambda x:x.str.contains("Python").sum())

Country
Afghanistan                              11
Albania                                  13
Algeria                                  40
Andorra                                   3
Angola                                    1
                                       ...
Venezuela, Bolivarian Republic of...     29
Viet Nam                                102
Yemen                                     1
Zambia                                    4
Zimbabwe                                 13
Name: LanguageWorkedWith, Length: 183, dtype: int64

In [71]:
country_grp["LanguageWorkedWith"].apply(lambda x:x.str.contains("Python").sum()).loc["India"]

2670

In [48]:
Python_res=country_grp["LanguageWorkedWith"].apply(lambda x:x.str.contains("Python").sum())

In [49]:
df["Country"].value_counts()

United States     12469
India              8403
United Kingdom     3896
Germany            3890
Canada             2191
                  ...
Lesotho               1
Kiribati              1
Nauru                 1
Grenada               1
Saint Lucia           1
Name: Country, Length: 183, dtype: int64

In [50]:
res=df["Country"].value_counts()

In [51]:
Python_res/res

Afghanistan                             0.130952
Albania                                 0.240741
Algeria                                 0.425532
Andorra                                 0.230769
Angola                                  0.111111
                                          ...
Venezuela, Bolivarian Republic of...    0.414286
Viet Nam                                0.280220
Yemen                                   0.142857
Zambia                                  0.190476
Zimbabwe                                0.419355
Length: 183, dtype: float64

In [52]:
(Python_res/res).nlargest()

Gabon                                 1.000000
Micronesia, Federated States of...    1.000000
Saint Lucia                           1.000000
Montenegro                            0.692308
Brunei Darussalam                     0.666667
dtype: float64

In [53]:
ctr_knows_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python', na=False).value_counts
                                                           (normalize=True))
ctr_knows_python.rename({False:'Don\'t know', True:'I know'}, inplace=True)
ctr_knows_python

Country
Afghanistan  Don't know    0.869048
             I know        0.130952
Albania      Don't know    0.759259
             I know        0.240741
Algeria      Don't know    0.574468
                             ...
Yemen        I know        0.142857
Zambia       Don't know    0.809524
             I know        0.190476
Zimbabwe     Don't know    0.580645
             I know        0.419355
Name: LanguageWorkedWith, Length: 344, dtype: float64

In [54]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python', na=False).value_counts
                                                           (normalize=True))

Country
Afghanistan  False    0.869048
             True     0.130952
Albania      False    0.759259
             True     0.240741
Algeria      False    0.574468
                        ...
Yemen        True     0.142857
Zambia       False    0.809524
             True     0.190476
Zimbabwe     False    0.580645
             True     0.419355
Name: LanguageWorkedWith, Length: 344, dtype: float64

In [55]:
type(ctr_knows_python)

pandas.core.series.Series

In [72]:
python_df=pd.concat([res,Python_res])

In [73]:
python_df

United States                           12469
India                                    8403
United Kingdom                           3896
Germany                                  3890
Canada                                   2191
                                        ...
Venezuela, Bolivarian Republic of...       29
Viet Nam                                  102
Yemen                                       1
Zambia                                      4
Zimbabwe                                   13
Length: 366, dtype: int64

In [74]:
python_df.loc["India"]

India    8403
India    2670
dtype: int64

In [58]:
python_df=pd.concat([res,Python_res],axis="columns",sort=False)

In [59]:
python_df

                Country  LanguageWorkedWith
United States     12469                5964
India              8403                2670
United Kingdom     3896                1621
Germany            3890                1712
Canada             2191                1011
...                 ...                 ...
Lesotho               1                   0
Kiribati              1                   0
Nauru                 1                   0
Grenada               1                   0
Saint Lucia           1                   1

[183 rows x 2 columns]

In [60]:
python_df.rename(columns={"Country":"Responder","LanguageWorkedWith":"Python_know"},inplace=True)

In [61]:
python_df

                Responder  Python_know
United States       12469         5964
India                8403         2670
United Kingdom       3896         1621
Germany              3890         1712
Canada               2191         1011
...                   ...          ...
Lesotho                 1            0
Kiribati                1            0
Nauru                   1            0
Grenada                 1            0
Saint Lucia             1            1

[183 rows x 2 columns]

In [62]:
python_df["pctknows_python"]=1/(python_df["Responder"]/python_df["Python_know"])*100

In [63]:
python_df

                Responder  Python_know  pctknows_python
United States       12469         5964        47.830620
India                8403         2670        31.774366
United Kingdom       3896         1621        41.606776
Germany              3890         1712        44.010283
Canada               2191         1011        46.143314
...                   ...          ...              ...
Lesotho                 1            0         0.000000
Kiribati                1            0         0.000000
Nauru                   1            0         0.000000
Grenada                 1            0         0.000000
Saint Lucia             1            1       100.000000

[183 rows x 3 columns]

In [64]:
python_df.sort_values(by="pctknows_python",ascending=False)

                                    Responder  Python_know  pctknows_python
Saint Lucia                                 1            1       100.000000
Gabon                                       1            1       100.000000
Micronesia, Federated States of...          1            1       100.000000
Montenegro                                 13            9        69.230769
Brunei Darussalam                           3            2        66.666667
...                                       ...          ...              ...
Burundi                                     2            0         0.000000
Cape Verde                                  2            0         0.000000
Monaco                                      2            0         0.000000
Saint Vincent and the Grenadines            3            0         0.000000
Antigua and Barbuda                         2            0         0.000000

[183 rows x 3 columns]

In [65]:
python_df.loc["India"]

Responder          8403.000000
Python_know        2670.000000
pctknows_python      31.774366
Name: India, dtype: float64